name: Security Scanning CI

on:
  push:
    branches:
      - master
      - security-scanning

  pull_request:
    branches:
      - master

jobs:

  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          if find . -name "*.py" -type f | grep -q .; then
            bandit -r . -f txt
          else
            echo "No Python files found. Bandit scan skipped."
          fi